### PR TITLE
2nd nixos meetup.

### PR DESCRIPTION
**Pull request by teh**

### CODE REVIEW

**Comment by Keats** [comment]
More details I think.
Something like "This is a hands-on meetup where we explain how the Nix language works and do something blabla"

**Comment by Keats** [comment]
Also maybe add that we will post slides after?

**Comment by teh** [comment]
Changed. Not sure about slides.

**Comment by Keats** [comment]
lgtm, i can deploy it if you want

**Comment by teh** [comment]
That'd be nice, I'll merge, thanks

**Pull request merged**
